### ISSUE TITLE
Type hints for Python module

### ISSUE THREAD

**Issue by ChristopherRabotin** [nyx-space/anise#336]
## Maintenance task description  

Using the work from https://github.com/nyx-space/hifitime/pull/335, add type hints in the Python module of ANISE.

## Scope of work

This task requires adding `:type param: PythonType` and `:rtype: PythonType2` to all of the functions available in Python.

## Priority 

Must be done after migrating to hifitime 4.0.0 since it provides the relevant Python documentation.

**Comment by translunar** [comment]
I want to +1 this. We absolutely can't use this module at my workplace if there are no typehints / pyi stubs.

**Comment by translunar** [comment]
To be clear, you're talking about pyi stubs, right?

**Comment by ChristopherRabotin** [comment]
That's correct. This ticket will automatically create an `anise.pyi` file similar to the newly added one in [hifitime](https://github.com/nyx-space/hifitime/blob/master/hifitime.pyi).
