### ISSUE TITLE
JPL daily high precision frame is always downloaded

### ISSUE THREAD

**Issue by gwbres** [nyx-space/anise#354]
# Bug report

## Describe the bug

Hello, the [QcContext](https://github.com/georust/rinex/blob/main/rinex-qc/src/context.rs#L235) holds the User data of our application and needs knowledge of an Earth Centered reference frame. At deployment we have this infaillible method that builds the Almanac that will be used for the entire session.

The targetted behavior is to try to obtain the daily JPL high precision, that we want to prefer, and use `IUA` frame model as a backup. 
This logic works.  Access to JPL database works from most lab stations, so the high precision scenario is naturally prefered.
But the problem is that ANISE does not seem to detect that the daily JPL has been previously downloaded and always generate a new download (to overwrite).

Note that RINEX-Qc uses ANISE V0.4.2, since it also requires Nyx and we're unable to upgrade yet. So, if this has been fixed in following version, please disregard this topic.

## To Reproduce

```bash
# download the georust toolkit
git clone https://github.com/georust/rinex
cargo build --all-features -r

# run a first survey with internet acces: JPL daily kernel is downloaded (~15s deployment).
./tutorials/QC/mojndnk.sh

# run a survey with internet acces: JPL daily kernel already exists, yet is re-downloaded (~15s deployment).
./tutorials/QC/mojndnk.sh
```

Are we misusing the API ? thank you

## Expected behavior

Ideally, ANISE should be smart enough to detect that the daily kernels already exist, and directly load them

## Platform

X86 modern PC

**Comment by gwbres** [comment]
> Are we misusing the API ? thank you

Crc32 is set to None in our `MetaFile` to describe the JPL Daily model. If I remember correctly, this is what makes ANISE trigger a download. 
Since this file is provided daily, we can't hardcode a value. From what I'm starting to understand, this is a problem on our side and we should have an option to evaluate the CRC of a possible existing file

**Comment by ChristopherRabotin** [comment]
Hi Guillaume,

Yes, if the CRC is set to `None`, then the MetaAlmanac will automatically redownload it, regardless of what's stored locally.

The solution is to load the meta file manually using `process` and then save this loaded structure using `dumps` because it will contain the CRC, cf. https://docs.rs/anise/0.4.2/anise/almanac/metaload/struct.MetaAlmanac.html#implementations .

I think the following would work:

```rust

let mut metaalmanac = MetaAlmanac::new("path-to-meta.dhall");
let almanac = metaalmanac.process().expect("could not download the latest data); // Builds the almanac.
let loaded_metalmanac = metaalmanac.dumps(); // This is a string.
// Now save that string back to `path-to-meta.dhall`.
```

Subsequent loads will only redownload the file if the CRC of the local copy is different from the CRC value in the metaalmanac. However, this means you'll need to manually remove that CRC if you need the daily JPL update. I'm not sure how to best implement this other functionality that expires the previously downloaded file, if that's something you need.

**Comment by ChristopherRabotin** [comment]
Hi @gwbres. Did this approach work?

**Comment by gwbres** [comment]
Hello, I should have time to test it this week end, will keep you updated.
It seems more reasonable than calculating the CRC myself, which should remain internal to the library

**Comment by gwbres** [comment]
thank you, we have a working solution 👍 
Tweaking the CRC32 ourselves obviously did the job, but we should not do that.
[This is one of the upgrades](https://github.com/rtk-rs/gnss-rtk/pull/54/files) yet I'm getting the feeling it is a little complex to obtain the expected results

**Comment by ChristopherRabotin** [comment]
Yes, the code you wrote seems more complicated than what I would expect. Did my proposed solution from [above](https://github.com/nyx-space/anise/issues/354#issuecomment-2509077234) not work?

**Comment by gwbres** [comment]
that's because it is not obvious that `metaalmanac.process()` downloads the 3 files I need, on first deployment especially.
I will git that a try in the next few days

**Comment by gwbres** [comment]
It turns out this is not trivial to create.
Because .process() will fail if any file in the batch is in failure, but .process() is my only option to download the fileset.
Actually I should move on to individual file management, and individual .process() calls.

While the JPL file is optional and ANISE is mandatory. ANISE is required on first deployment ever which means network access is required on first deployment ever. 

On following deployments:

* if JPL model has never been initiated (not mentioned in the fileset) I introduce an option to try to update it
* if JPL model has been initiated we're fine for the model's validity with local backup storage
* and we have an option to attempt a new update
